In [1]:
import torch

/home/alice/.local/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


### Creating Tensor
- randn
- eye
- arange
- linspace
- ones, zeros, ones_Like
- from_numpy

In [41]:
x = torch.randn(3, 3)
mask = torch.eye(3)
x * mask

tensor([[-1.6457,  0.0000, -0.0000],
        [-0.0000, -0.5441, -0.0000],
        [ 0.0000, -0.0000, -0.9620]])

In [48]:
ones = torch.ones((10, ), dtype=torch.int64)
zeros = torch.zeros_like(ones)
ones, zeros

(tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))

In [72]:
import numpy as np
x = np.random.randint(0, 10, (4, 4))
x = torch.from_numpy(x)
x

tensor([[9, 1, 1, 1],
        [1, 5, 7, 4],
        [1, 7, 7, 6],
        [4, 9, 4, 0]])

### Basic Operations
- stack
- cat
- view
- reshape
- permute
- split
- chunk
- transpose
- squeeze, unsqueeze
- flatten

In [78]:
x0 = torch.arange(6)
x1 = x0.flip(-1)
x = torch.stack([x0, x1])

In [79]:
y = torch.cat([x0, x0])
print(y)
y = y.view(2, -1) # -1 means autocomplete
print(y)
y = y.transpose(-1, -2) # can index from end
print(y)
(y1, y2, y3) = y.chunk(3, dim=0)
print(y2)


tensor([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5])
tensor([[0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5]])
tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4],
        [5, 5]])
tensor([[2, 2],
        [3, 3]])


In [ ]:
x = torch.randn(1, 3, 3)
print(x)
y = x.squeeze(0)
print(y)
z = y.unsqueeze(-1)
print(z)

### Tensor Properties
- size
- shape
- device
- dtype
- numel

In [8]:
floatTensor = torch.Tensor(4, 5)
longTensor = torch.LongTensor(10,)

# size
print(f"size: {floatTensor.size(0)}")

# shape
print(f"shape: {floatTensor.shape}")

# device
print(f"device: {floatTensor.device}")

# dtype
print(f"dtype: {longTensor.dtype}")

# numel
print(f"numel: {floatTensor.numel()}")



size: 4
shape: torch.Size([4, 5])
device: cpu
dtype: torch.int64
numel: 20


In [70]:
h = torch.randn(64, 3, 24, 24)
h_channel_last = h.permute(0, 2, 3, 1)
h.shape, h_channel_last.shape

(torch.Size([64, 3, 24, 24]), torch.Size([64, 24, 24, 3]))

### Mathematical Operations
- sum()
- min(), max()
- amin(), amax()
- mean(), std()
- exp, log, sin, cos..

In [14]:
x = torch.arange(10)
x = torch.stack([x, x])
sumx = x.sum(dim=-1, keepdim=True)
sumx

tensor([[45],
        [45]])

In [26]:
x = torch.randn((4, 5))
mx, midx = x.max(dim=-1, keepdim=True)
x-mx, midx

(tensor([[-2.1113, -0.5264,  0.0000, -1.6144, -0.9955],
         [ 0.0000, -1.7270, -1.4226, -1.3898, -1.2882],
         [-0.9258, -1.9417, -2.4162,  0.0000, -0.1270],
         [-2.1631, -1.5114, -3.2638, -1.2700,  0.0000]]),
 tensor([[2],
         [0],
         [3],
         [4]]))

In [33]:
x = torch.linspace(0, 2*torch.pi, 100)
torch.allclose(x.sin()**2 + x.cos()**2, torch.ones(100))

True